@startuml
start

:开始使用任务单APP;
if (是否需要设置提醒?) then (是)
  :设置提醒;
  if (提醒类型是DDL吗?) then (是)
    :设置DDL提醒;
  else (否)
    :自定义提醒时间与方式;
  endif
else (否)
  :跳过提醒设置;
endif

:任务归类与标签设计;
:按时间排序分块显示任务;

if (任务是日常任务吗?) then (是)
  :区分日程与日常任务;
else (否)
  :设置重复任务;
endif

:选择任务重要性与难度;
:优先级加权系统;

if (需要自定义UI风格吗?) then (是)
  :选择UI风格;
else (否)
  :使用默认风格;
endif

if (需要帮助吗?) then (是)
  :查看帮助文档与教程;
else (否)
  :跳过帮助;
endif

:任务统计与归档;
:增加、删除、修改任务;

stop
@enduml